# Content: Configuration file for the training and classification pipelines
# See README.md for more information about each parameter

n_processes: 32 # positive integer
device: 'cuda' # 'cpu' or 'cuda'
no_log: False # True or False

# the following parameters are only relevant for classification

model_type: "comprehensive" # 'light' or 'comprehensive'
models: # models to use for classification
- kegg
- interpro
- orthodb
- eggnog
chunksize: 20000 # positive integer
batch_size: 32
num_epochs: 10

# the following parameters are only relevant for the training preprocessing pipeline

mmseqs_n_processes: 4 # positive integer
sampled_sequences_per_subcluster: 60 # 'use_all' or positive integer
fraction_of_sampled_unknown_sequences: 1.0 # 'use_all', 'do_not_use', or 0 <= float <= 1.0
samples_profiles_product_limit: 150_000_000_000_000 # positive integer
create_subclusters: True # True (creates comprehensive model, equivalent to --create-subclusters) or False (creates light model, equivalent to --no-create-subclusters)
mmseqs_cluster_coverage: 0.8 # 0 <= float <= 1.0
mmseqs_cluster_identity: 0.9 # 0 <= float <= 1.0
mmseqs_cluster_coverage_subclusters: 0.5 # 0 <= float <= 1.0
sequences_max_len_product_limit: 500_000_000 # positive integer
save_every: 100000 # positive integer
log_to_wandb: True # True or False
wandb_project: 'famus'
wandb_api_key_path: "wandb_api_key.txt"
