{% set name = "famus" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.11
    - pip
    - setuptools
  run:
    - python >=3.11
    - numpy >=1.26.4
    - pandas >=2.2.3
    - scikit-learn >=1.3.0
    - biopython >=1.78
    - tqdm >=4.66.2
    - matplotlib >=3.10.1
    - seaborn >=0.13.2
    - pytorch >=2.2.0
    # Add external tools as conda dependencies
    - hmmer
    - mafft
    - seqkit

test:
  imports:
    - famus
  commands:
    - python -c "import famus"
    - hmmalign -h
    - mafft --help
    - seqkit version

about:
  home: https://github.com/burstein-lab/famus
  license_family: MIT
  license: MIT
  license_file: LICENSE
  summary: 'Functional Annotation Method Using Siamese neural networks (FAMUS)'
